### ISSUE TITLE
Could you add build instructions?

### ISSUE THREAD

**Issue by edeguine** [isering/WoodPixel#2]
Hi, I tried to build with cmake --build . 

but I get multiple errors. Could you advise on build requirements?
`cmake --build .
Scanning dependencies of target trlib
[  1%] Building CXX object lib/CMakeFiles/trlib.dir/affine_transformation.cpp.o
[  3%] Building CXX object lib/CMakeFiles/trlib.dir/bezier_curve.cpp.o
In file included from /Users/etienne/WoodPixel/lib/bezier_curve.cpp:33:
In file included from /Users/etienne/WoodPixel/lib/bezier_curve.hpp:34:
/Users/etienne/WoodPixel/lib/serializable.hpp:66:10: error: missing 'typename' prior to dependent type name 'std::vector<T>::const_iterator'
    for (std::vector<T>::const_iterator iter = vec.begin(); iter != vec.end(); ++iter)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         typename 
/Users/etienne/WoodPixel/lib/serializable.hpp:104:10: error: missing 'typename' prior to dependent type name 'std::vector<cv::Point_<T> >::const_iterator'
    for (std::vector<cv::Point_<T>>::const_iterator iter = vec.begin(); iter != vec.end(); ++iter)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         typename 
In file included from /Users/etienne/WoodPixel/lib/bezier_curve.cpp:24:
In file included from /Users/etienne/WoodPixel/lib/config.h:1:
In file included from /Users/etienne/WoodPixel/lib/print_debug.hpp:26:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/string:500:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/string_view:176:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__string:56:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/algorithm:644:
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:1880:61: error: object expression of non-scalar type 'double [2][2]' cannot be used in a pseudo-destructor expression
    _LIBCPP_INLINE_VISIBILITY void destroy(pointer __p) {__p->~_Tp();}
                                                         ~~~^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:1742:18: note: in instantiation of member function 'std::__1::allocator<double [2][2]>::destroy' requested here
            {__a.destroy(__p);}
                 ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:1595:14: note: in instantiation of function template specialization 'std::__1::allocator_traits<std::__1::allocator<double [2][2]> >::__destroy<double [2][2]>' requested here
            {__destroy(__has_destroy<allocator_type, _Tp*>(), __a, __p);}
             ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/vector:421:25: note: in instantiation of function template specialization 'std::__1::allocator_traits<std::__1::allocator<double [2][2]> >::destroy<double [2][2]>' requested here
        __alloc_traits::destroy(__alloc(), _VSTD::__to_raw_pointer(--__soon_to_be_end));
                        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/vector:364:29: note: in instantiation of member function 'std::__1::__vector_base<double [2][2], std::__1::allocator<double [2][2]> >::__destruct_at_end' requested here
    void clear() _NOEXCEPT {__destruct_at_end(__begin_);}
                            ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/vector:458:9: note: in instantiation of member function 'std::__1::__vector_base<double [2][2], std::__1::allocator<double [2][2]> >::clear' requested here
        clear();
        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1427:74: note: in instantiation of member function 'std::__1::__vector_base<double [2][2], std::__1::allocator<double [2][2]> >::~__vector_base' requested here
    template <class _Tp, class _Alloc> friend class _LIBCPP_TEMPLATE_VIS vector;
                                                                         ^
3 errors generated.
make[2]: *** [lib/CMakeFiles/trlib.dir/bezier_curve.cpp.o] Error 1
make[1]: *** [lib/CMakeFiles/trlib.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by jaydsteele** [comment]
I'm also running into similar issues, some simple build instructions would be very helpful

**Comment by isering** [comment]
Sorry for the late response. I updated the project to compile with gcc 9.3 and added build instructions for a minimal installation of Ubuntu 20.04.1. Please let me know if you encounter any more problems.
